# deploy:
#   provider: pages  => commit to gh-pages branch
#   skip_cleanup: true
#   github_token: $GITHUB_TOKEN
#   keep_history: true
#   on:
#     branch: develop

branches:
  only:
    - master
    - develop
    - "/release*/"

language: python - "3.6"

before_install:
  - echo "test starts"
  - pip install codecov coverage

install:
  - pip install .[develop]

script:
  # - pytest
  - py.test --cov-report=xml --cov=twinpy tests/

after_success:
  - codecov
