deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: develop

branches:
  only:
    - master
    - develop
    - "/release*/"

language: python - "3.6"

before_install:
  - echo "test starts"
  - pip install codecov

install:
  - pip install .[develop]

script:
  - pytest

after_success:
  - codecov
  # - bash <(curl -s https://codecov.io/bash)
