# deploy:
#   provider: pages  => commit to gh-pages branch
#   skip_cleanup: true
#   github_token: $GITHUB_TOKEN
#   keep_history: true
#   on:
#     branch: develop

branches:
  only:
    - master
    - develop
    - "/release*/"
    - "/feature*/"

language: python - "3.7"

before_install:
  - echo "test starts"
  - pip install codecov coverage pytest-cov

install:
  - pip install .[develop]

script:
  - pytest --verbose --color=yes --cov=twinpy --assert=plain

after_success:
  - codecov
