deploy:
  provider: pages
  skip_cleanup: true
  # github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: gh-pages
branches:
  only:
    - develop

language: python - "3.6"

before_install:
  # - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O $HOME/miniconda3.sh
  # - chmod +x $HOME/miniconda3.sh
  # - "$HOME/miniconda3.sh -b;"
  # - export PATH=/home/travis/miniconda3/bin:$PATH
  # - export PYTHONPATH=/home/travis/build/kei0822kei/package-template:$PYTHONPATH
  # - conda update --yes -n base -c defaults conda
  - echo "test starts"

install:
  # - conda install --yes python="3.6" sphinx
  # - pip install --user travis-sphinx
  - pip install .[develop]

script:
  # - echo $TRAVIS_BRANCH
  # - [ "$TRAVIS_BRANCH" == "gh-pages" ]; then travis-sphinx build
  - pytest

after_success:
  # - [ "$TRAVIS_BRANCH" == "gh-pages" ]; then travis-sphinx deploy
  - echo "tset finishes"
