deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: gh-pages
branches:
  only:
  - gh-pages

language: python - "3.6"

# before_install will simply setup a conda enviroment for installing python packages, if you
# have project dependencies it's usually recommended to go this route
# before_install:
#     # - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
#     - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
#     - chmod +x miniconda.sh
#     - "./miniconda.sh -b"
#     - export PATH=/home/travis/miniconda2/bin:$PATH
#     - conda update --yes conda
#       # - sudo rm -rf /dev/shm
#     - sudo ln -s /run/shm /dev/shm
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O $HOME/miniconda3.sh
  - chmod +x $HOME/miniconda3.sh
  - "$HOME/miniconda3.sh -b;"
  - export PATH=/home/travis/miniconda3/bin:$PATH
  - export PYTHONPATH=/home/travis/build/kei0822kei/package-template:$PYTHONPATH
  - conda update --yes -n base -c defaults conda

install:
    - conda install --yes python="3.6" sphinx
    - pip install --user travis-sphinx

script:
    - echo $TRAVIS_BRANCH
    - [ "$TRAVIS_BRANCH" == "gh-pages" ]; then travis-sphinx build

after_success:
    - [ "$TRAVIS_BRANCH" == "gh-pages" ]; then travis-sphinx deploy
