deploy:
  provider: pages
  skip_cleanup: true
  keep_history: true
  on:
    branch: develop

branches:
  only:
    - master
    - develop
    - "/release*/"

language: python - "3.6"

before_install:
  - echo "test starts"

install:
  - pip install .[develop]

script:
  - pytest

after_success:
  - codecov
